### ISSUE TITLE
x = 'foo' x = 'bar' parsing

### ISSUE THREAD

**Issue by BenasPaulikas** [isaacs/ini#37]
Hello, in my .ini file I have 

ServerPackages=Core
ServerPackages=Engine
....

After parsing it leaves only 1 ServerPackages line, how this can be fixed ?

**Comment by kodypeterson** [comment]
I think it needs to be:

ServerPackages[]=Core
ServerPackages[]=Engine

This is the way ini's arrays seem to work

**Comment by BenasPaulikas** [comment]
Yeah, it would be great but the .ini file is provided by other application, I know it's dumb to assign multiple values to the same "variable", if I do name[] = value1 name[] = value2 app isn't working.

**Comment by kodypeterson** [comment]
I would suggest some sort of middle parser...

Something that would read the input add the [] and then pass it to the parser.

None the less probably not a problem with this library.

**Comment by BenasPaulikas** [comment]
Can you reccommend such middle parser ? Or I should do it by hand like string.replace('ServerPackages','ServerPackages[]') ?

**Comment by hotamy** [comment]
I have same problem ...
Have solution it?

**Comment by isaacs** [comment]
Duplicate of https://github.com/isaacs/ini/issues/52

(Technically https://github.com/isaacs/ini/issues/52 is a duplicate of this, but that's more clearly stated, and probably @robertkowalski will give you what you want :)

**Comment by robertkowalski** [comment]
see here: https://github.com/npm/ini/issues/52#issuecomment-188531495
